# l10n.yaml (extension specific options)

# Enable translation 
translate: true              

# Auto run flutter gen-l10n               
generate : true       

# Key prefix for translation             
key-prefix: context.loc.  

# Generate key name 
# "ask" : prompt with pre-filled text | true : infer from text | false : prompt  
auto-name-key: true       

# Language to use for key name                  
key-name-language: en       

# Import line if needed                
import-line: ""      
synthetic-package: false
arb-dir: lib/l10n
output-dir: lib/l10n/output
output-localization-file: app_localization.dart
use-escaping: true
nullable-getter: false
English-arb-file: app_en.arb
Japanese-arb-file: app_ja.arb
Korean-arb-file: app_ko.arb
Russian-arb-file: app_ru.arb
Vietnamese-arb-file: app_vi.arb
Chinese-arb-file: app_zh.arb
